### ISSUE TITLE
BAG API v2 - Features

### ISSUE THREAD

**Issue by chithract** [lvbag/BAG-API#10]
I just checked BAG API v2 version and have the following quick questions:

1) I have tried to get the residences with a valid id, it shows internal server error. If we give an invalid city id, it gives the 400 response ( with params validation message). Is this a known issue?

2) Could you please tell us the approximate date for adding the search by address feature?

Thanks,
Chithra

**Comment by lvbag** [comment]
1. 
I can't reproduse this errosr. 
The request for getting residenses works for me.
https://api.acceptatie.kadaster.nl/lvbag/api/individuelebevragingen/v2/woonplaatsen/3595

With an invalid city id, I get a 404 response

2. 
The adress feature for the Individuele Bevragingen API will probably be implemented in Q3.

**Comment by twjhendriks** [comment]
Hallo,

How can I get all the verblijfsobjecten from a city.
This works:
https://api.acceptatie.kadaster.nl/lvbag/api/individuelebevragingen/v2/woonplaatsen/2735
but how can I dig deeper?

Tom

**Comment by NicoleKortoomsBAG** [comment]
Hello Tom,
You would need functionalities that are not yet implemented in test.
There will an api to get all openbare ruimten in a woonplaats and to get all nummeraanduidingen on a openbare ruimte. 
It would take multiple requests.

**Comment by twjhendriks** [comment]
Thanks so I have to use version1 to get this information?
Do I need an other api-key for that?

**Comment by NicoleKortoomsBAG** [comment]
Please take notice that this new v2 api will be implemented because of the new law for BAG. Therefore the  current api's will be end of live next year. 
I don't know everything about the current api's but I hope this information will help you.

There is an XML api in which it is possible to do this requests.  https://zakelijk.kadaster.nl/-/bag-bevragen. It works with a subscription. 
There is also a RestJson api but I don't think you do the same requests. I can see that you can find the nummeraanduiding with the parameter postcode, but not the streets or postcodes in a woonplaats. This api works with an api-key. Information about the restjson api can be found on https://bag.basisregistraties.overheid.nl/restful-api# .
