### ISSUE TITLE
The expand on the GET /nummeraanduidingen seems not working

### ISSUE THREAD

**Issue by roland-d** [lvbag/BAG-API#14]
Hello,

When I call the GET endpoint `{{baseUrl}}/nummeraanduidingen?postcode=3192VR&huisnummer=146&exacteMatch=true&expand=true` there are two things I notice:
1. It returns all the houses on this street, I would think it should only return the one that matches the zipcode and housenumber
2. The `expand` true doesn't give any embedded results. So I tried also `expand=ligtInWoonplaats` but this doesn't give any embedded value either.

Could you explain what the expected behavior is?

**Comment by lvbag** [comment]
Hi Roland,
I am afraid to say it, but you are testing a not in test implemented endpoint again. The only reason you are getting a response is because this endpoint was used to implement paging. So if you would like to test that, here you go.
The only endpoints that are testable are the objects with the object id (Actueel en Peildatum). 
Expand won't be part of the first release except for the expand in Woonplaatsen.

**Comment by roland-d** [comment]
Hello,

No worries, I realize I am testing against a work in progress :) Just happy to share my experiences with you as an end-user. I can confirm that pagination is working 😃 

Thank you for the fast answer.
