### ISSUE TITLE
Bagviewer.kadaster - Checking the new changes

### ISSUE THREAD

**Issue by chithract** [lvbag/BAG-API#31]
Can we view the below pages/check the results online after the API upgrade:

https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=Abcoud
https://bagviewer.kadaster.nl/lvbag/bag-viewer/api/bag/bevragen?objectIds=0899300000249338

Could you please confirm? Thanks in advance.

**Comment by NicoleKortoomsBAG** [comment]
Hi,
I am a little confused, since your question is about the API, but your request is directed to the BAG viewer, which is a different BAG product. The viewer is meant for customers that want to search and view BAG data online in a viewer. The BAG viewer gives real time BAG data. 
Your second request only gives data, the viewer is not meant for that kind of use. Other products like the BAG API are more suitable. If you are not sure which product you can use best for your usecase, you can check the BAG beslisboom for help.
https://github.com/lvbag/BAG-API/tree/master/Beslisboom%20BAG%202.0%20producten 
Kind regards,
Nicole Kortooms

**Comment by chithract** [comment]
Hi,

Thanks for the clarification.

I was a little bit confused about bagviewer product and API. I used those URLs to view the results.

Could you please let me know the API endpoint that can be used with ObjectIds?

Thanks.

**Comment by NicoleKortoomsBAG** [comment]
I see you are using the ID of a Openbare Ruimte and are receiving the information about the Openbare Ruimte and the Woonplaats. The url you could use to get this information is:
https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/openbareruimten/0899300000249338?expand=ligtInWoonplaats

Every object has it's own endpoints. You can find all the endpoints in the technical specification and documentation on this Github page. 

You will need an API Key. You can get one at https://formulieren.kadaster.nl/aanvraag_bag_api_individuele_bevragingen_productie or https://formulieren.kadaster.nl/aanvraag_bag_api_individuele_bevragingen_test if you would like to test first.

**Comment by chithract** [comment]
Thanks for the hint. I had a quick look at the documentation and swagger.io.

I've already test API key. The objectid does not always need to be an Openbare Ruimte. It can be anything, for example - Verblijfsobject - https://bagviewer.kadaster.nl/lvbag/bag-viewer/api/bag/bevragen?objectIds=0451010000007271

(i)Can we have a common endpoint to get the resultset from objectid irrelevant of type? 
(ii) Will there be any changes in https://bagviewer.kadaster.nl/lvbag/bag-viewer/api/bag/ with this release?

**Comment by NicoleKortoomsBAG** [comment]
I am not sure we're talking about the same thing. The base URL of the new BAG API in domain test is: https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/.
The URL you're sending your request to, is to serve information in our viewer. 

Could you please tell me more about your usecase so I can get a better impression of the functionality you need?

**Comment by chithract** [comment]
Hi,

I am checking API with https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/ itself.

We need to confirm/compare it with Bagviewer page also. That's why I am clarifying that.

Need to implement this:

1) Need an endpoint for getting matches with the keywords:

This works with a test API key:
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adressen/zoek?zoek=Aagje%20Dekenlaan%205%20Amstelveen&page=1&pageSize=20

2) Need an endpoint to get the below details with (VERBLIJFSOBJECT ID):
- displayString
- hoofdadres->postcode
- panden->bouwjaar
The above details can be seen here:
https://bagviewer.kadaster.nl/lvbag/bag-viewer/api/bag/bevragen?objectIds=0362200000000048 (comparing data)

I tried this with 
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2//verblijfsobjecten/0362200000000048

But it didn't work. Could you please confirm the above two cases?

**Comment by chithract** [comment]
Regarding the second point:

I tried this with https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adressen/0362200000000048 and it worked.

(i) The doubt is how to get displayString shown here (https://bagviewer.kadaster.nl/lvbag/bag-viewer/api/bag/bevragen?objectIds=0362200000000048) with the above endpoint.

(ii) panden->bouwjaar

I tried https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/panden/0362100001067173. But it gives precondition failed error.

<img width="1400" alt="Screenshot 2021-02-10 at 6 24 43 PM" src="https://user-images.githubusercontent.com/10785422/107512764-4977fc80-6bcd-11eb-8602-0c2e1c8087d0.png">

Please help with the above two points.

Thanks,
Chithra

**Comment by NicoleKortoomsBAG** [comment]
Hi Chithra,
For the BAG viewer we also use this API to get the information. So the results you are getting are always the same if you're using the same endpoints.

For the first case I think you have an address and want to check if it really (still) exists. 
You are using the search functionality which is great if you're not exactly sure what your are looking for, but as you can see you are looking for number 5, but in the result set also numbers 51, 53 etc are given. 
In case you want to check if your address really exists and is spelled right, you could also consider another endpoint. But only if you should have the complete and exact address.
If you use the endpoint below for your search, in the results will only be only all number 5's. Maybe with results like 5a and 5b1 etc. 
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?woonplaatsNaam=Amstelveen&openbareRuimteNaam=Aagje%20Dekenlaan&huisnummer=5

If you always have the exact address you can use exacteMatch and you will only get the adress that has an exact match. Since your address doesn't have any huisletters or huisnummertoevoegingen I used another address for the example. This features is explained in the 'featurebeschrijvingen' on this Github page.

https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?woonplaatsNaam=%27s-Gravenhage&openbareRuimteNaam=Bezuidenhoutseweg&huisnummer=265
(16 matches)
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adressen?woonplaatsNaam=%27s-Gravenhage&openbareRuimteNaam=Bezuidenhoutseweg&huisnummer=265&exacteMatch=true
(1 match)

For your second usecase you are using a nummeraanduiding ID and not a adresseerbaarobject ID. 
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/nummeraanduidingen/0362200000000048
However this endpoint won't give the information you are looking for.

To get all the information you need in one request, you can use:
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/adressenuitgebreid/0362200000000048

adressenuitgebreid can also be used with a postcode, huisnummer, of woonplaats, openbare ruimte en huisnummer (exacteMatch is possible)
https://api.bag.test.kadaster.nl/lvbag/individuelebevragingen/v2/adressenuitgebreid?woonplaatsNaam=Amstelveen&openbareRuimteNaam=aagje%20dekenlaan&huisnummer=55

Because this enpoint and the panden endpoint contain geometry you'll need to use an accept-Crs in the header which is epsg:28992.

I hope this helps,
Nicole

**Comment by chithract** [comment]
Hi Nicole,

Thanks for your help. Could you please let me know when the new version available? Will API V1 available till the end of March?

Thanks.

**Comment by NicoleKortoomsBAG** [comment]
The API BAG Individuele Bevragingen is already in production.
It will be possible to use the v1 API until October, but de data won't be up to date than. From April the data won't be updated.
