### ISSUE TITLE
"verblijfsobjecten" edpoint technical specification doesn't match reality

### ISSUE THREAD

**Issue by kmalinovsky** [lvbag/BAG-API#52]
There is problem with endpoint /verblijfsobjecten/{id} (probably with whole group)
https://api.bag.acceptatie.kadaster.nl/lvbag/individuelebevragingen/v2/verblijfsobjecten/0226010000038820

Technical specification claims, that "gebruiksdoelen" parameter is required, minimal length = 1. Response from uri above doesn't match this rule.
Also "Accept-Crs" header parameter isn't marked as required, but call without it ends up with http 412.

Please align claimed rules with actual situation.

![image](https://user-images.githubusercontent.com/98458047/151146898-b119598d-f551-4c26-8a45-7d4ad5432b4d.png)

**Comment by NicoleKortoomsBAG** [comment]
Thank you for pointing out 'gebruiksdoelen' wasn't filled. We fixed this in the test database.

For the Accept-CRS.
Because not all endpoints that can contain geometry always do (woonplaatsen), the param isn't marked required. 
In this case the user should follow the logic that the param Accept-CRS is required when the response contains geometry.
